/*
SOPHON Encoding API

Testing DownloadsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sophon

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Liqhtworks/sophon-sdk-go"
)

func Test_sophon_DownloadsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DownloadsAPIService Download", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var token string

		resp, httpRes, err := apiClient.DownloadsAPI.Download(context.Background(), token).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
