/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// JobSourceType Discriminator for `JobSource` variants.
type JobSourceType string

// List of JobSourceType
const (
	UPLOAD JobSourceType = "upload"
)

// All allowed values of JobSourceType enum
var AllowedJobSourceTypeEnumValues = []JobSourceType{
	"upload",
}

func (v *JobSourceType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JobSourceType(value)
	for _, existing := range AllowedJobSourceTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid JobSourceType", value)
}

// NewJobSourceTypeFromValue returns a pointer to a valid JobSourceType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewJobSourceTypeFromValue(v string) (*JobSourceType, error) {
	ev := JobSourceType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for JobSourceType: valid values are %v", v, AllowedJobSourceTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v JobSourceType) IsValid() bool {
	for _, existing := range AllowedJobSourceTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to JobSourceType value
func (v JobSourceType) Ptr() *JobSourceType {
	return &v
}

type NullableJobSourceType struct {
	value *JobSourceType
	isSet bool
}

func (v NullableJobSourceType) Get() *JobSourceType {
	return v.value
}

func (v *NullableJobSourceType) Set(val *JobSourceType) {
	v.value = val
	v.isSet = true
}

func (v NullableJobSourceType) IsSet() bool {
	return v.isSet
}

func (v *NullableJobSourceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobSourceType(val *JobSourceType) *NullableJobSourceType {
	return &NullableJobSourceType{value: val, isSet: true}
}

func (v NullableJobSourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobSourceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

