/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the JobProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobProgress{}

// JobProgress struct for JobProgress
type JobProgress struct {
	// Current processing stage label (e.g. \"probing\", \"encoding\", \"muxing\").
	Stage *string `json:"stage,omitempty"`
	// Canonical pipeline phase used for progress semantics.
	Phase JobStatus `json:"phase"`
	Percent float32 `json:"percent"`
	// Progress within the current phase. Null before active processing.
	PhasePercent *float32 `json:"phase_percent,omitempty"`
	Fps *float32 `json:"fps,omitempty"`
	EtaSeconds *int32 `json:"eta_seconds,omitempty"`
	FramesDone *int32 `json:"frames_done,omitempty"`
	FramesTotal *int32 `json:"frames_total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JobProgress JobProgress

// NewJobProgress instantiates a new JobProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobProgress(phase JobStatus, percent float32) *JobProgress {
	this := JobProgress{}
	this.Phase = phase
	this.Percent = percent
	return &this
}

// NewJobProgressWithDefaults instantiates a new JobProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobProgressWithDefaults() *JobProgress {
	this := JobProgress{}
	return &this
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *JobProgress) GetStage() string {
	if o == nil || IsNil(o.Stage) {
		var ret string
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetStageOk() (*string, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *JobProgress) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given string and assigns it to the Stage field.
func (o *JobProgress) SetStage(v string) {
	o.Stage = &v
}

// GetPhase returns the Phase field value
func (o *JobProgress) GetPhase() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetPhaseOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase, true
}

// SetPhase sets field value
func (o *JobProgress) SetPhase(v JobStatus) {
	o.Phase = v
}

// GetPercent returns the Percent field value
func (o *JobProgress) GetPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percent
}

// GetPercentOk returns a tuple with the Percent field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetPercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percent, true
}

// SetPercent sets field value
func (o *JobProgress) SetPercent(v float32) {
	o.Percent = v
}

// GetPhasePercent returns the PhasePercent field value if set, zero value otherwise.
func (o *JobProgress) GetPhasePercent() float32 {
	if o == nil || IsNil(o.PhasePercent) {
		var ret float32
		return ret
	}
	return *o.PhasePercent
}

// GetPhasePercentOk returns a tuple with the PhasePercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetPhasePercentOk() (*float32, bool) {
	if o == nil || IsNil(o.PhasePercent) {
		return nil, false
	}
	return o.PhasePercent, true
}

// HasPhasePercent returns a boolean if a field has been set.
func (o *JobProgress) HasPhasePercent() bool {
	if o != nil && !IsNil(o.PhasePercent) {
		return true
	}

	return false
}

// SetPhasePercent gets a reference to the given float32 and assigns it to the PhasePercent field.
func (o *JobProgress) SetPhasePercent(v float32) {
	o.PhasePercent = &v
}

// GetFps returns the Fps field value if set, zero value otherwise.
func (o *JobProgress) GetFps() float32 {
	if o == nil || IsNil(o.Fps) {
		var ret float32
		return ret
	}
	return *o.Fps
}

// GetFpsOk returns a tuple with the Fps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetFpsOk() (*float32, bool) {
	if o == nil || IsNil(o.Fps) {
		return nil, false
	}
	return o.Fps, true
}

// HasFps returns a boolean if a field has been set.
func (o *JobProgress) HasFps() bool {
	if o != nil && !IsNil(o.Fps) {
		return true
	}

	return false
}

// SetFps gets a reference to the given float32 and assigns it to the Fps field.
func (o *JobProgress) SetFps(v float32) {
	o.Fps = &v
}

// GetEtaSeconds returns the EtaSeconds field value if set, zero value otherwise.
func (o *JobProgress) GetEtaSeconds() int32 {
	if o == nil || IsNil(o.EtaSeconds) {
		var ret int32
		return ret
	}
	return *o.EtaSeconds
}

// GetEtaSecondsOk returns a tuple with the EtaSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetEtaSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.EtaSeconds) {
		return nil, false
	}
	return o.EtaSeconds, true
}

// HasEtaSeconds returns a boolean if a field has been set.
func (o *JobProgress) HasEtaSeconds() bool {
	if o != nil && !IsNil(o.EtaSeconds) {
		return true
	}

	return false
}

// SetEtaSeconds gets a reference to the given int32 and assigns it to the EtaSeconds field.
func (o *JobProgress) SetEtaSeconds(v int32) {
	o.EtaSeconds = &v
}

// GetFramesDone returns the FramesDone field value if set, zero value otherwise.
func (o *JobProgress) GetFramesDone() int32 {
	if o == nil || IsNil(o.FramesDone) {
		var ret int32
		return ret
	}
	return *o.FramesDone
}

// GetFramesDoneOk returns a tuple with the FramesDone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetFramesDoneOk() (*int32, bool) {
	if o == nil || IsNil(o.FramesDone) {
		return nil, false
	}
	return o.FramesDone, true
}

// HasFramesDone returns a boolean if a field has been set.
func (o *JobProgress) HasFramesDone() bool {
	if o != nil && !IsNil(o.FramesDone) {
		return true
	}

	return false
}

// SetFramesDone gets a reference to the given int32 and assigns it to the FramesDone field.
func (o *JobProgress) SetFramesDone(v int32) {
	o.FramesDone = &v
}

// GetFramesTotal returns the FramesTotal field value if set, zero value otherwise.
func (o *JobProgress) GetFramesTotal() int32 {
	if o == nil || IsNil(o.FramesTotal) {
		var ret int32
		return ret
	}
	return *o.FramesTotal
}

// GetFramesTotalOk returns a tuple with the FramesTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobProgress) GetFramesTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.FramesTotal) {
		return nil, false
	}
	return o.FramesTotal, true
}

// HasFramesTotal returns a boolean if a field has been set.
func (o *JobProgress) HasFramesTotal() bool {
	if o != nil && !IsNil(o.FramesTotal) {
		return true
	}

	return false
}

// SetFramesTotal gets a reference to the given int32 and assigns it to the FramesTotal field.
func (o *JobProgress) SetFramesTotal(v int32) {
	o.FramesTotal = &v
}

func (o JobProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	toSerialize["phase"] = o.Phase
	toSerialize["percent"] = o.Percent
	if !IsNil(o.PhasePercent) {
		toSerialize["phase_percent"] = o.PhasePercent
	}
	if !IsNil(o.Fps) {
		toSerialize["fps"] = o.Fps
	}
	if !IsNil(o.EtaSeconds) {
		toSerialize["eta_seconds"] = o.EtaSeconds
	}
	if !IsNil(o.FramesDone) {
		toSerialize["frames_done"] = o.FramesDone
	}
	if !IsNil(o.FramesTotal) {
		toSerialize["frames_total"] = o.FramesTotal
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JobProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phase",
		"percent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobProgress := _JobProgress{}

	err = json.Unmarshal(data, &varJobProgress)

	if err != nil {
		return err
	}

	*o = JobProgress(varJobProgress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "stage")
		delete(additionalProperties, "phase")
		delete(additionalProperties, "percent")
		delete(additionalProperties, "phase_percent")
		delete(additionalProperties, "fps")
		delete(additionalProperties, "eta_seconds")
		delete(additionalProperties, "frames_done")
		delete(additionalProperties, "frames_total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJobProgress struct {
	value *JobProgress
	isSet bool
}

func (v NullableJobProgress) Get() *JobProgress {
	return v.value
}

func (v *NullableJobProgress) Set(val *JobProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableJobProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableJobProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobProgress(val *JobProgress) *NullableJobProgress {
	return &NullableJobProgress{value: val, isSet: true}
}

func (v NullableJobProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


