/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the JobSourceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobSourceInfo{}

// JobSourceInfo struct for JobSourceInfo
type JobSourceInfo struct {
	// Original file name of the source.
	Name *string `json:"name,omitempty"`
	Bytes *int64 `json:"bytes,omitempty"`
	// SHA-256 hex digest of the source file.
	Sha256 string `json:"sha256"`
	DurationSeconds *float64 `json:"duration_seconds,omitempty"`
	Resolution *string `json:"resolution,omitempty"`
	FrameRate *string `json:"frame_rate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JobSourceInfo JobSourceInfo

// NewJobSourceInfo instantiates a new JobSourceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobSourceInfo(sha256 string) *JobSourceInfo {
	this := JobSourceInfo{}
	this.Sha256 = sha256
	return &this
}

// NewJobSourceInfoWithDefaults instantiates a new JobSourceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobSourceInfoWithDefaults() *JobSourceInfo {
	this := JobSourceInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *JobSourceInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *JobSourceInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *JobSourceInfo) SetName(v string) {
	o.Name = &v
}

// GetBytes returns the Bytes field value if set, zero value otherwise.
func (o *JobSourceInfo) GetBytes() int64 {
	if o == nil || IsNil(o.Bytes) {
		var ret int64
		return ret
	}
	return *o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.Bytes) {
		return nil, false
	}
	return o.Bytes, true
}

// HasBytes returns a boolean if a field has been set.
func (o *JobSourceInfo) HasBytes() bool {
	if o != nil && !IsNil(o.Bytes) {
		return true
	}

	return false
}

// SetBytes gets a reference to the given int64 and assigns it to the Bytes field.
func (o *JobSourceInfo) SetBytes(v int64) {
	o.Bytes = &v
}

// GetSha256 returns the Sha256 field value
func (o *JobSourceInfo) GetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha256, true
}

// SetSha256 sets field value
func (o *JobSourceInfo) SetSha256(v string) {
	o.Sha256 = v
}

// GetDurationSeconds returns the DurationSeconds field value if set, zero value otherwise.
func (o *JobSourceInfo) GetDurationSeconds() float64 {
	if o == nil || IsNil(o.DurationSeconds) {
		var ret float64
		return ret
	}
	return *o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetDurationSecondsOk() (*float64, bool) {
	if o == nil || IsNil(o.DurationSeconds) {
		return nil, false
	}
	return o.DurationSeconds, true
}

// HasDurationSeconds returns a boolean if a field has been set.
func (o *JobSourceInfo) HasDurationSeconds() bool {
	if o != nil && !IsNil(o.DurationSeconds) {
		return true
	}

	return false
}

// SetDurationSeconds gets a reference to the given float64 and assigns it to the DurationSeconds field.
func (o *JobSourceInfo) SetDurationSeconds(v float64) {
	o.DurationSeconds = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *JobSourceInfo) GetResolution() string {
	if o == nil || IsNil(o.Resolution) {
		var ret string
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetResolutionOk() (*string, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *JobSourceInfo) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given string and assigns it to the Resolution field.
func (o *JobSourceInfo) SetResolution(v string) {
	o.Resolution = &v
}

// GetFrameRate returns the FrameRate field value if set, zero value otherwise.
func (o *JobSourceInfo) GetFrameRate() string {
	if o == nil || IsNil(o.FrameRate) {
		var ret string
		return ret
	}
	return *o.FrameRate
}

// GetFrameRateOk returns a tuple with the FrameRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSourceInfo) GetFrameRateOk() (*string, bool) {
	if o == nil || IsNil(o.FrameRate) {
		return nil, false
	}
	return o.FrameRate, true
}

// HasFrameRate returns a boolean if a field has been set.
func (o *JobSourceInfo) HasFrameRate() bool {
	if o != nil && !IsNil(o.FrameRate) {
		return true
	}

	return false
}

// SetFrameRate gets a reference to the given string and assigns it to the FrameRate field.
func (o *JobSourceInfo) SetFrameRate(v string) {
	o.FrameRate = &v
}

func (o JobSourceInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobSourceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Bytes) {
		toSerialize["bytes"] = o.Bytes
	}
	toSerialize["sha256"] = o.Sha256
	if !IsNil(o.DurationSeconds) {
		toSerialize["duration_seconds"] = o.DurationSeconds
	}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	if !IsNil(o.FrameRate) {
		toSerialize["frame_rate"] = o.FrameRate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JobSourceInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobSourceInfo := _JobSourceInfo{}

	err = json.Unmarshal(data, &varJobSourceInfo)

	if err != nil {
		return err
	}

	*o = JobSourceInfo(varJobSourceInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "bytes")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "duration_seconds")
		delete(additionalProperties, "resolution")
		delete(additionalProperties, "frame_rate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJobSourceInfo struct {
	value *JobSourceInfo
	isSet bool
}

func (v NullableJobSourceInfo) Get() *JobSourceInfo {
	return v.value
}

func (v *NullableJobSourceInfo) Set(val *JobSourceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableJobSourceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableJobSourceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobSourceInfo(val *JobSourceInfo) *NullableJobSourceInfo {
	return &NullableJobSourceInfo{value: val, isSet: true}
}

func (v NullableJobSourceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobSourceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


