/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUploadRequest{}

// CreateUploadRequest struct for CreateUploadRequest
type CreateUploadRequest struct {
	FileName string `json:"file_name"`
	// Total file size in bytes.
	FileSize int64 `json:"file_size"`
	MimeType string `json:"mime_type"`
	AdditionalProperties map[string]interface{}
}

type _CreateUploadRequest CreateUploadRequest

// NewCreateUploadRequest instantiates a new CreateUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUploadRequest(fileName string, fileSize int64, mimeType string) *CreateUploadRequest {
	this := CreateUploadRequest{}
	this.FileName = fileName
	this.FileSize = fileSize
	this.MimeType = mimeType
	return &this
}

// NewCreateUploadRequestWithDefaults instantiates a new CreateUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUploadRequestWithDefaults() *CreateUploadRequest {
	this := CreateUploadRequest{}
	return &this
}

// GetFileName returns the FileName field value
func (o *CreateUploadRequest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *CreateUploadRequest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *CreateUploadRequest) SetFileName(v string) {
	o.FileName = v
}

// GetFileSize returns the FileSize field value
func (o *CreateUploadRequest) GetFileSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value
// and a boolean to check if the value has been set.
func (o *CreateUploadRequest) GetFileSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileSize, true
}

// SetFileSize sets field value
func (o *CreateUploadRequest) SetFileSize(v int64) {
	o.FileSize = v
}

// GetMimeType returns the MimeType field value
func (o *CreateUploadRequest) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *CreateUploadRequest) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *CreateUploadRequest) SetMimeType(v string) {
	o.MimeType = v
}

func (o CreateUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_name"] = o.FileName
	toSerialize["file_size"] = o.FileSize
	toSerialize["mime_type"] = o.MimeType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_name",
		"file_size",
		"mime_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUploadRequest := _CreateUploadRequest{}

	err = json.Unmarshal(data, &varCreateUploadRequest)

	if err != nil {
		return err
	}

	*o = CreateUploadRequest(varCreateUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_name")
		delete(additionalProperties, "file_size")
		delete(additionalProperties, "mime_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUploadRequest struct {
	value *CreateUploadRequest
	isSet bool
}

func (v NullableCreateUploadRequest) Get() *CreateUploadRequest {
	return v.value
}

func (v *NullableCreateUploadRequest) Set(val *CreateUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUploadRequest(val *CreateUploadRequest) *NullableCreateUploadRequest {
	return &NullableCreateUploadRequest{value: val, isSet: true}
}

func (v NullableCreateUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


