/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WebhookDeliveryPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryPayload{}

// WebhookDeliveryPayload Payload delivered to registered webhook endpoints on terminal job events. Signed with HMAC-SHA256 over `\"{timestamp}.{raw_body}\"` using the per-webhook secret. Consumers must verify the signature before processing. 
type WebhookDeliveryPayload struct {
	// Unique delivery event ID for deduplication.
	EventId string `json:"event_id"`
	// Event type.
	Type string `json:"type"`
	// ISO 8601 timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The job that reached a terminal state.
	JobId string `json:"job_id"`
	// Terminal job status.
	Status string `json:"status"`
	// Opaque metadata from the original job submission.
	Metadata map[string]interface{} `json:"metadata"`
	AdditionalProperties map[string]interface{}
}

type _WebhookDeliveryPayload WebhookDeliveryPayload

// NewWebhookDeliveryPayload instantiates a new WebhookDeliveryPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryPayload(eventId string, type_ string, timestamp time.Time, jobId string, status string, metadata map[string]interface{}) *WebhookDeliveryPayload {
	this := WebhookDeliveryPayload{}
	this.EventId = eventId
	this.Type = type_
	this.Timestamp = timestamp
	this.JobId = jobId
	this.Status = status
	this.Metadata = metadata
	return &this
}

// NewWebhookDeliveryPayloadWithDefaults instantiates a new WebhookDeliveryPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryPayloadWithDefaults() *WebhookDeliveryPayload {
	this := WebhookDeliveryPayload{}
	return &this
}

// GetEventId returns the EventId field value
func (o *WebhookDeliveryPayload) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *WebhookDeliveryPayload) SetEventId(v string) {
	o.EventId = v
}

// GetType returns the Type field value
func (o *WebhookDeliveryPayload) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WebhookDeliveryPayload) SetType(v string) {
	o.Type = v
}

// GetTimestamp returns the Timestamp field value
func (o *WebhookDeliveryPayload) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WebhookDeliveryPayload) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetJobId returns the JobId field value
func (o *WebhookDeliveryPayload) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *WebhookDeliveryPayload) SetJobId(v string) {
	o.JobId = v
}

// GetStatus returns the Status field value
func (o *WebhookDeliveryPayload) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookDeliveryPayload) SetStatus(v string) {
	o.Status = v
}

// GetMetadata returns the Metadata field value
func (o *WebhookDeliveryPayload) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryPayload) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *WebhookDeliveryPayload) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o WebhookDeliveryPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["type"] = o.Type
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["job_id"] = o.JobId
	toSerialize["status"] = o.Status
	toSerialize["metadata"] = o.Metadata

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookDeliveryPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"type",
		"timestamp",
		"job_id",
		"status",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookDeliveryPayload := _WebhookDeliveryPayload{}

	err = json.Unmarshal(data, &varWebhookDeliveryPayload)

	if err != nil {
		return err
	}

	*o = WebhookDeliveryPayload(varWebhookDeliveryPayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "job_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookDeliveryPayload struct {
	value *WebhookDeliveryPayload
	isSet bool
}

func (v NullableWebhookDeliveryPayload) Get() *WebhookDeliveryPayload {
	return v.value
}

func (v *NullableWebhookDeliveryPayload) Set(val *WebhookDeliveryPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryPayload(val *WebhookDeliveryPayload) *NullableWebhookDeliveryPayload {
	return &NullableWebhookDeliveryPayload{value: val, isSet: true}
}

func (v NullableWebhookDeliveryPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


