/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the UploadJobSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadJobSource{}

// UploadJobSource Source backed by a completed chunked upload session.
type UploadJobSource struct {
	Type JobSourceType `json:"type"`
	// ID of a completed upload session.
	UploadId string `json:"upload_id"`
	AdditionalProperties map[string]interface{}
}

type _UploadJobSource UploadJobSource

// NewUploadJobSource instantiates a new UploadJobSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadJobSource(type_ JobSourceType, uploadId string) *UploadJobSource {
	this := UploadJobSource{}
	this.Type = type_
	this.UploadId = uploadId
	return &this
}

// NewUploadJobSourceWithDefaults instantiates a new UploadJobSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadJobSourceWithDefaults() *UploadJobSource {
	this := UploadJobSource{}
	return &this
}

// GetType returns the Type field value
func (o *UploadJobSource) GetType() JobSourceType {
	if o == nil {
		var ret JobSourceType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UploadJobSource) GetTypeOk() (*JobSourceType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UploadJobSource) SetType(v JobSourceType) {
	o.Type = v
}

// GetUploadId returns the UploadId field value
func (o *UploadJobSource) GetUploadId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value
// and a boolean to check if the value has been set.
func (o *UploadJobSource) GetUploadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadId, true
}

// SetUploadId sets field value
func (o *UploadJobSource) SetUploadId(v string) {
	o.UploadId = v
}

func (o UploadJobSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadJobSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["upload_id"] = o.UploadId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UploadJobSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"upload_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadJobSource := _UploadJobSource{}

	err = json.Unmarshal(data, &varUploadJobSource)

	if err != nil {
		return err
	}

	*o = UploadJobSource(varUploadJobSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "upload_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUploadJobSource struct {
	value *UploadJobSource
	isSet bool
}

func (v NullableUploadJobSource) Get() *UploadJobSource {
	return v.value
}

func (v *NullableUploadJobSource) Set(val *UploadJobSource) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadJobSource) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadJobSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadJobSource(val *UploadJobSource) *NullableUploadJobSource {
	return &NullableUploadJobSource{value: val, isSet: true}
}

func (v NullableUploadJobSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadJobSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


