/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateJobRequest{}

// CreateJobRequest struct for CreateJobRequest
type CreateJobRequest struct {
	Source UploadJobSource `json:"source"`
	Profile JobProfile `json:"profile"`
	Output *CreateJobOutputOptions `json:"output,omitempty"`
	// IDs of registered webhook endpoints to notify on job state changes.
	WebhookIds []string `json:"webhook_ids,omitempty"`
	// Arbitrary key-value metadata attached to the job. Max 16 KiB serialized.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateJobRequest CreateJobRequest

// NewCreateJobRequest instantiates a new CreateJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJobRequest(source UploadJobSource, profile JobProfile) *CreateJobRequest {
	this := CreateJobRequest{}
	this.Source = source
	this.Profile = profile
	return &this
}

// NewCreateJobRequestWithDefaults instantiates a new CreateJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJobRequestWithDefaults() *CreateJobRequest {
	this := CreateJobRequest{}
	return &this
}

// GetSource returns the Source field value
func (o *CreateJobRequest) GetSource() UploadJobSource {
	if o == nil {
		var ret UploadJobSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetSourceOk() (*UploadJobSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CreateJobRequest) SetSource(v UploadJobSource) {
	o.Source = v
}

// GetProfile returns the Profile field value
func (o *CreateJobRequest) GetProfile() JobProfile {
	if o == nil {
		var ret JobProfile
		return ret
	}

	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetProfileOk() (*JobProfile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Profile, true
}

// SetProfile sets field value
func (o *CreateJobRequest) SetProfile(v JobProfile) {
	o.Profile = v
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *CreateJobRequest) GetOutput() CreateJobOutputOptions {
	if o == nil || IsNil(o.Output) {
		var ret CreateJobOutputOptions
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetOutputOk() (*CreateJobOutputOptions, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *CreateJobRequest) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given CreateJobOutputOptions and assigns it to the Output field.
func (o *CreateJobRequest) SetOutput(v CreateJobOutputOptions) {
	o.Output = &v
}

// GetWebhookIds returns the WebhookIds field value if set, zero value otherwise.
func (o *CreateJobRequest) GetWebhookIds() []string {
	if o == nil || IsNil(o.WebhookIds) {
		var ret []string
		return ret
	}
	return o.WebhookIds
}

// GetWebhookIdsOk returns a tuple with the WebhookIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetWebhookIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhookIds) {
		return nil, false
	}
	return o.WebhookIds, true
}

// HasWebhookIds returns a boolean if a field has been set.
func (o *CreateJobRequest) HasWebhookIds() bool {
	if o != nil && !IsNil(o.WebhookIds) {
		return true
	}

	return false
}

// SetWebhookIds gets a reference to the given []string and assigns it to the WebhookIds field.
func (o *CreateJobRequest) SetWebhookIds(v []string) {
	o.WebhookIds = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateJobRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateJobRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateJobRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o CreateJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["profile"] = o.Profile
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	if !IsNil(o.WebhookIds) {
		toSerialize["webhook_ids"] = o.WebhookIds
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"profile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateJobRequest := _CreateJobRequest{}

	err = json.Unmarshal(data, &varCreateJobRequest)

	if err != nil {
		return err
	}

	*o = CreateJobRequest(varCreateJobRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "profile")
		delete(additionalProperties, "output")
		delete(additionalProperties, "webhook_ids")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateJobRequest struct {
	value *CreateJobRequest
	isSet bool
}

func (v NullableCreateJobRequest) Get() *CreateJobRequest {
	return v.value
}

func (v *NullableCreateJobRequest) Set(val *CreateJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJobRequest(val *CreateJobRequest) *NullableCreateJobRequest {
	return &NullableCreateJobRequest{value: val, isSet: true}
}

func (v NullableCreateJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


