/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the ErrorEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorEnvelope{}

// ErrorEnvelope struct for ErrorEnvelope
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
	AdditionalProperties map[string]interface{}
}

type _ErrorEnvelope ErrorEnvelope

// NewErrorEnvelope instantiates a new ErrorEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorEnvelope(error_ ErrorBody) *ErrorEnvelope {
	this := ErrorEnvelope{}
	this.Error = error_
	return &this
}

// NewErrorEnvelopeWithDefaults instantiates a new ErrorEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorEnvelopeWithDefaults() *ErrorEnvelope {
	this := ErrorEnvelope{}
	return &this
}

// GetError returns the Error field value
func (o *ErrorEnvelope) GetError() ErrorBody {
	if o == nil {
		var ret ErrorBody
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ErrorEnvelope) GetErrorOk() (*ErrorBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ErrorEnvelope) SetError(v ErrorBody) {
	o.Error = v
}

func (o ErrorEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ErrorEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorEnvelope := _ErrorEnvelope{}

	err = json.Unmarshal(data, &varErrorEnvelope)

	if err != nil {
		return err
	}

	*o = ErrorEnvelope(varErrorEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableErrorEnvelope struct {
	value *ErrorEnvelope
	isSet bool
}

func (v NullableErrorEnvelope) Get() *ErrorEnvelope {
	return v.value
}

func (v *NullableErrorEnvelope) Set(val *ErrorEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorEnvelope(val *ErrorEnvelope) *NullableErrorEnvelope {
	return &NullableErrorEnvelope{value: val, isSet: true}
}

func (v NullableErrorEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


