/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the UploadPartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPartResponse{}

// UploadPartResponse struct for UploadPartResponse
type UploadPartResponse struct {
	PartNumber int64 `json:"part_number"`
	Received bool `json:"received"`
	AdditionalProperties map[string]interface{}
}

type _UploadPartResponse UploadPartResponse

// NewUploadPartResponse instantiates a new UploadPartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPartResponse(partNumber int64, received bool) *UploadPartResponse {
	this := UploadPartResponse{}
	this.PartNumber = partNumber
	this.Received = received
	return &this
}

// NewUploadPartResponseWithDefaults instantiates a new UploadPartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPartResponseWithDefaults() *UploadPartResponse {
	this := UploadPartResponse{}
	return &this
}

// GetPartNumber returns the PartNumber field value
func (o *UploadPartResponse) GetPartNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *UploadPartResponse) GetPartNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *UploadPartResponse) SetPartNumber(v int64) {
	o.PartNumber = v
}

// GetReceived returns the Received field value
func (o *UploadPartResponse) GetReceived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Received
}

// GetReceivedOk returns a tuple with the Received field value
// and a boolean to check if the value has been set.
func (o *UploadPartResponse) GetReceivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Received, true
}

// SetReceived sets field value
func (o *UploadPartResponse) SetReceived(v bool) {
	o.Received = v
}

func (o UploadPartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["part_number"] = o.PartNumber
	toSerialize["received"] = o.Received

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UploadPartResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"part_number",
		"received",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadPartResponse := _UploadPartResponse{}

	err = json.Unmarshal(data, &varUploadPartResponse)

	if err != nil {
		return err
	}

	*o = UploadPartResponse(varUploadPartResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "part_number")
		delete(additionalProperties, "received")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUploadPartResponse struct {
	value *UploadPartResponse
	isSet bool
}

func (v NullableUploadPartResponse) Get() *UploadPartResponse {
	return v.value
}

func (v *NullableUploadPartResponse) Set(val *UploadPartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPartResponse(val *UploadPartResponse) *NullableUploadPartResponse {
	return &NullableUploadPartResponse{value: val, isSet: true}
}

func (v NullableUploadPartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


