/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
)

// checks if the CreateJobOutputOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateJobOutputOptions{}

// CreateJobOutputOptions Optional output shaping knobs for a new job.
type CreateJobOutputOptions struct {
	Container *OutputContainer `json:"container,omitempty"`
	// When true, audio is included in the output. MKV preserves source audio streams unchanged. MP4 preserves broadly compatible source audio codecs when possible, and may normalize incompatible codecs to AAC for playback compatibility. When false, the output is video only. 
	Audio *bool `json:"audio,omitempty"`
	// Target output height in pixels. When set, output is scaled down (aspect ratio preserved, width derived from source, both dims rounded to even). If absent or larger than source height, output uses source dimensions. Billing tier is determined by the actual encoded output, not by this requested value. 
	TargetHeight *int32 `json:"target_height,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateJobOutputOptions CreateJobOutputOptions

// NewCreateJobOutputOptions instantiates a new CreateJobOutputOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJobOutputOptions() *CreateJobOutputOptions {
	this := CreateJobOutputOptions{}
	var container OutputContainer = MP4
	this.Container = &container
	var audio bool = false
	this.Audio = &audio
	return &this
}

// NewCreateJobOutputOptionsWithDefaults instantiates a new CreateJobOutputOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJobOutputOptionsWithDefaults() *CreateJobOutputOptions {
	this := CreateJobOutputOptions{}
	var container OutputContainer = MP4
	this.Container = &container
	var audio bool = false
	this.Audio = &audio
	return &this
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *CreateJobOutputOptions) GetContainer() OutputContainer {
	if o == nil || IsNil(o.Container) {
		var ret OutputContainer
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobOutputOptions) GetContainerOk() (*OutputContainer, bool) {
	if o == nil || IsNil(o.Container) {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *CreateJobOutputOptions) HasContainer() bool {
	if o != nil && !IsNil(o.Container) {
		return true
	}

	return false
}

// SetContainer gets a reference to the given OutputContainer and assigns it to the Container field.
func (o *CreateJobOutputOptions) SetContainer(v OutputContainer) {
	o.Container = &v
}

// GetAudio returns the Audio field value if set, zero value otherwise.
func (o *CreateJobOutputOptions) GetAudio() bool {
	if o == nil || IsNil(o.Audio) {
		var ret bool
		return ret
	}
	return *o.Audio
}

// GetAudioOk returns a tuple with the Audio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobOutputOptions) GetAudioOk() (*bool, bool) {
	if o == nil || IsNil(o.Audio) {
		return nil, false
	}
	return o.Audio, true
}

// HasAudio returns a boolean if a field has been set.
func (o *CreateJobOutputOptions) HasAudio() bool {
	if o != nil && !IsNil(o.Audio) {
		return true
	}

	return false
}

// SetAudio gets a reference to the given bool and assigns it to the Audio field.
func (o *CreateJobOutputOptions) SetAudio(v bool) {
	o.Audio = &v
}

// GetTargetHeight returns the TargetHeight field value if set, zero value otherwise.
func (o *CreateJobOutputOptions) GetTargetHeight() int32 {
	if o == nil || IsNil(o.TargetHeight) {
		var ret int32
		return ret
	}
	return *o.TargetHeight
}

// GetTargetHeightOk returns a tuple with the TargetHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobOutputOptions) GetTargetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetHeight) {
		return nil, false
	}
	return o.TargetHeight, true
}

// HasTargetHeight returns a boolean if a field has been set.
func (o *CreateJobOutputOptions) HasTargetHeight() bool {
	if o != nil && !IsNil(o.TargetHeight) {
		return true
	}

	return false
}

// SetTargetHeight gets a reference to the given int32 and assigns it to the TargetHeight field.
func (o *CreateJobOutputOptions) SetTargetHeight(v int32) {
	o.TargetHeight = &v
}

func (o CreateJobOutputOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateJobOutputOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Container) {
		toSerialize["container"] = o.Container
	}
	if !IsNil(o.Audio) {
		toSerialize["audio"] = o.Audio
	}
	if !IsNil(o.TargetHeight) {
		toSerialize["target_height"] = o.TargetHeight
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateJobOutputOptions) UnmarshalJSON(data []byte) (err error) {
	varCreateJobOutputOptions := _CreateJobOutputOptions{}

	err = json.Unmarshal(data, &varCreateJobOutputOptions)

	if err != nil {
		return err
	}

	*o = CreateJobOutputOptions(varCreateJobOutputOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "container")
		delete(additionalProperties, "audio")
		delete(additionalProperties, "target_height")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateJobOutputOptions struct {
	value *CreateJobOutputOptions
	isSet bool
}

func (v NullableCreateJobOutputOptions) Get() *CreateJobOutputOptions {
	return v.value
}

func (v *NullableCreateJobOutputOptions) Set(val *CreateJobOutputOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJobOutputOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJobOutputOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJobOutputOptions(val *CreateJobOutputOptions) *NullableCreateJobOutputOptions {
	return &NullableCreateJobOutputOptions{value: val, isSet: true}
}

func (v NullableCreateJobOutputOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJobOutputOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


