/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the CompleteUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompleteUploadResponse{}

// CompleteUploadResponse struct for CompleteUploadResponse
type CompleteUploadResponse struct {
	Id string `json:"id"`
	Status string `json:"status"`
	// SHA-256 hex digest of the assembled file.
	Sha256 string `json:"sha256"`
	Bytes int64 `json:"bytes"`
	AdditionalProperties map[string]interface{}
}

type _CompleteUploadResponse CompleteUploadResponse

// NewCompleteUploadResponse instantiates a new CompleteUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompleteUploadResponse(id string, status string, sha256 string, bytes int64) *CompleteUploadResponse {
	this := CompleteUploadResponse{}
	this.Id = id
	this.Status = status
	this.Sha256 = sha256
	this.Bytes = bytes
	return &this
}

// NewCompleteUploadResponseWithDefaults instantiates a new CompleteUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompleteUploadResponseWithDefaults() *CompleteUploadResponse {
	this := CompleteUploadResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CompleteUploadResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CompleteUploadResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CompleteUploadResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *CompleteUploadResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CompleteUploadResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CompleteUploadResponse) SetStatus(v string) {
	o.Status = v
}

// GetSha256 returns the Sha256 field value
func (o *CompleteUploadResponse) GetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value
// and a boolean to check if the value has been set.
func (o *CompleteUploadResponse) GetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha256, true
}

// SetSha256 sets field value
func (o *CompleteUploadResponse) SetSha256(v string) {
	o.Sha256 = v
}

// GetBytes returns the Bytes field value
func (o *CompleteUploadResponse) GetBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *CompleteUploadResponse) GetBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *CompleteUploadResponse) SetBytes(v int64) {
	o.Bytes = v
}

func (o CompleteUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompleteUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["sha256"] = o.Sha256
	toSerialize["bytes"] = o.Bytes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CompleteUploadResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"sha256",
		"bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompleteUploadResponse := _CompleteUploadResponse{}

	err = json.Unmarshal(data, &varCompleteUploadResponse)

	if err != nil {
		return err
	}

	*o = CompleteUploadResponse(varCompleteUploadResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCompleteUploadResponse struct {
	value *CompleteUploadResponse
	isSet bool
}

func (v NullableCompleteUploadResponse) Get() *CompleteUploadResponse {
	return v.value
}

func (v *NullableCompleteUploadResponse) Set(val *CompleteUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompleteUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompleteUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompleteUploadResponse(val *CompleteUploadResponse) *NullableCompleteUploadResponse {
	return &NullableCompleteUploadResponse{value: val, isSet: true}
}

func (v NullableCompleteUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompleteUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


