/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the ReadyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReadyResponse{}

// ReadyResponse struct for ReadyResponse
type ReadyResponse struct {
	Ready bool `json:"ready"`
	// Names of failed readiness checks (database, disk_critical, draining, workers_dead).
	ChecksFailed []string `json:"checks_failed,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReadyResponse ReadyResponse

// NewReadyResponse instantiates a new ReadyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadyResponse(ready bool) *ReadyResponse {
	this := ReadyResponse{}
	this.Ready = ready
	return &this
}

// NewReadyResponseWithDefaults instantiates a new ReadyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadyResponseWithDefaults() *ReadyResponse {
	this := ReadyResponse{}
	return &this
}

// GetReady returns the Ready field value
func (o *ReadyResponse) GetReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ready
}

// GetReadyOk returns a tuple with the Ready field value
// and a boolean to check if the value has been set.
func (o *ReadyResponse) GetReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ready, true
}

// SetReady sets field value
func (o *ReadyResponse) SetReady(v bool) {
	o.Ready = v
}

// GetChecksFailed returns the ChecksFailed field value if set, zero value otherwise.
func (o *ReadyResponse) GetChecksFailed() []string {
	if o == nil || IsNil(o.ChecksFailed) {
		var ret []string
		return ret
	}
	return o.ChecksFailed
}

// GetChecksFailedOk returns a tuple with the ChecksFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReadyResponse) GetChecksFailedOk() ([]string, bool) {
	if o == nil || IsNil(o.ChecksFailed) {
		return nil, false
	}
	return o.ChecksFailed, true
}

// HasChecksFailed returns a boolean if a field has been set.
func (o *ReadyResponse) HasChecksFailed() bool {
	if o != nil && !IsNil(o.ChecksFailed) {
		return true
	}

	return false
}

// SetChecksFailed gets a reference to the given []string and assigns it to the ChecksFailed field.
func (o *ReadyResponse) SetChecksFailed(v []string) {
	o.ChecksFailed = v
}

func (o ReadyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReadyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ready"] = o.Ready
	if !IsNil(o.ChecksFailed) {
		toSerialize["checks_failed"] = o.ChecksFailed
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReadyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ready",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReadyResponse := _ReadyResponse{}

	err = json.Unmarshal(data, &varReadyResponse)

	if err != nil {
		return err
	}

	*o = ReadyResponse(varReadyResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ready")
		delete(additionalProperties, "checks_failed")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReadyResponse struct {
	value *ReadyResponse
	isSet bool
}

func (v NullableReadyResponse) Get() *ReadyResponse {
	return v.value
}

func (v *NullableReadyResponse) Set(val *ReadyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReadyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReadyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadyResponse(val *ReadyResponse) *NullableReadyResponse {
	return &NullableReadyResponse{value: val, isSet: true}
}

func (v NullableReadyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


