/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// JobProfile Encoding profile ID. Coffee-themed naming: prep time maps to encode speed, bare name is the 8-bit default (universal decoder compatibility), `-10bit` suffix opts into HEVC Main10 for higher-quality playback on newer decoders.  **8-bit (default):** - `sophon-espresso` — fastest, lowest compression - `sophon-cortado` — balanced speed and quality - `sophon-americano` — slowest, highest compression  **10-bit (HEVC Main10):** - `sophon-espresso-10bit` - `sophon-cortado-10bit` - `sophon-americano-10bit`  **Adaptive dispatcher:** - `sophon-auto` — public opt-in profile. The worker classifies   the source and records the concrete `effective_profile_id` on   the job once dispatch resolves. 
type JobProfile string

// List of JobProfile
const (
	SOPHON_ESPRESSO JobProfile = "sophon-espresso"
	SOPHON_CORTADO JobProfile = "sophon-cortado"
	SOPHON_AMERICANO JobProfile = "sophon-americano"
	SOPHON_ESPRESSO_10BIT JobProfile = "sophon-espresso-10bit"
	SOPHON_CORTADO_10BIT JobProfile = "sophon-cortado-10bit"
	SOPHON_AMERICANO_10BIT JobProfile = "sophon-americano-10bit"
	SOPHON_AUTO JobProfile = "sophon-auto"
)

// All allowed values of JobProfile enum
var AllowedJobProfileEnumValues = []JobProfile{
	"sophon-espresso",
	"sophon-cortado",
	"sophon-americano",
	"sophon-espresso-10bit",
	"sophon-cortado-10bit",
	"sophon-americano-10bit",
	"sophon-auto",
}

func (v *JobProfile) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JobProfile(value)
	for _, existing := range AllowedJobProfileEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid JobProfile", value)
}

// NewJobProfileFromValue returns a pointer to a valid JobProfile
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewJobProfileFromValue(v string) (*JobProfile, error) {
	ev := JobProfile(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for JobProfile: valid values are %v", v, AllowedJobProfileEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v JobProfile) IsValid() bool {
	for _, existing := range AllowedJobProfileEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to JobProfile value
func (v JobProfile) Ptr() *JobProfile {
	return &v
}

type NullableJobProfile struct {
	value *JobProfile
	isSet bool
}

func (v NullableJobProfile) Get() *JobProfile {
	return v.value
}

func (v *NullableJobProfile) Set(val *JobProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableJobProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableJobProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobProfile(val *JobProfile) *NullableJobProfile {
	return &NullableJobProfile{value: val, isSet: true}
}

func (v NullableJobProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

