/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UploadStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadStatusResponse{}

// UploadStatusResponse struct for UploadStatusResponse
type UploadStatusResponse struct {
	Id string `json:"id"`
	Status string `json:"status"`
	FileName string `json:"file_name"`
	TotalChunks int32 `json:"total_chunks"`
	// Array of 0-indexed part numbers that have been received.
	ReceivedChunks []int32 `json:"received_chunks"`
	ExpiresAt time.Time `json:"expires_at"`
	// Source media width in pixels, populated from ffprobe after upload assembly. Null for uploads in `initiated`/`uploading` state or when probe failed. 
	SourceWidth *int32 `json:"source_width,omitempty"`
	// Source media height in pixels. See `source_width`.
	SourceHeight *int32 `json:"source_height,omitempty"`
	// Source media duration in seconds, from ffprobe after upload assembly. Used by the webapp free-tier budget check to compute realistic billable_seconds (5-second ceiling rounding). 
	SourceDurationSeconds *float32 `json:"source_duration_seconds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UploadStatusResponse UploadStatusResponse

// NewUploadStatusResponse instantiates a new UploadStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadStatusResponse(id string, status string, fileName string, totalChunks int32, receivedChunks []int32, expiresAt time.Time) *UploadStatusResponse {
	this := UploadStatusResponse{}
	this.Id = id
	this.Status = status
	this.FileName = fileName
	this.TotalChunks = totalChunks
	this.ReceivedChunks = receivedChunks
	this.ExpiresAt = expiresAt
	return &this
}

// NewUploadStatusResponseWithDefaults instantiates a new UploadStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadStatusResponseWithDefaults() *UploadStatusResponse {
	this := UploadStatusResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UploadStatusResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UploadStatusResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *UploadStatusResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UploadStatusResponse) SetStatus(v string) {
	o.Status = v
}

// GetFileName returns the FileName field value
func (o *UploadStatusResponse) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *UploadStatusResponse) SetFileName(v string) {
	o.FileName = v
}

// GetTotalChunks returns the TotalChunks field value
func (o *UploadStatusResponse) GetTotalChunks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalChunks
}

// GetTotalChunksOk returns a tuple with the TotalChunks field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetTotalChunksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalChunks, true
}

// SetTotalChunks sets field value
func (o *UploadStatusResponse) SetTotalChunks(v int32) {
	o.TotalChunks = v
}

// GetReceivedChunks returns the ReceivedChunks field value
func (o *UploadStatusResponse) GetReceivedChunks() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.ReceivedChunks
}

// GetReceivedChunksOk returns a tuple with the ReceivedChunks field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetReceivedChunksOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceivedChunks, true
}

// SetReceivedChunks sets field value
func (o *UploadStatusResponse) SetReceivedChunks(v []int32) {
	o.ReceivedChunks = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *UploadStatusResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *UploadStatusResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetSourceWidth returns the SourceWidth field value if set, zero value otherwise.
func (o *UploadStatusResponse) GetSourceWidth() int32 {
	if o == nil || IsNil(o.SourceWidth) {
		var ret int32
		return ret
	}
	return *o.SourceWidth
}

// GetSourceWidthOk returns a tuple with the SourceWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetSourceWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.SourceWidth) {
		return nil, false
	}
	return o.SourceWidth, true
}

// HasSourceWidth returns a boolean if a field has been set.
func (o *UploadStatusResponse) HasSourceWidth() bool {
	if o != nil && !IsNil(o.SourceWidth) {
		return true
	}

	return false
}

// SetSourceWidth gets a reference to the given int32 and assigns it to the SourceWidth field.
func (o *UploadStatusResponse) SetSourceWidth(v int32) {
	o.SourceWidth = &v
}

// GetSourceHeight returns the SourceHeight field value if set, zero value otherwise.
func (o *UploadStatusResponse) GetSourceHeight() int32 {
	if o == nil || IsNil(o.SourceHeight) {
		var ret int32
		return ret
	}
	return *o.SourceHeight
}

// GetSourceHeightOk returns a tuple with the SourceHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetSourceHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.SourceHeight) {
		return nil, false
	}
	return o.SourceHeight, true
}

// HasSourceHeight returns a boolean if a field has been set.
func (o *UploadStatusResponse) HasSourceHeight() bool {
	if o != nil && !IsNil(o.SourceHeight) {
		return true
	}

	return false
}

// SetSourceHeight gets a reference to the given int32 and assigns it to the SourceHeight field.
func (o *UploadStatusResponse) SetSourceHeight(v int32) {
	o.SourceHeight = &v
}

// GetSourceDurationSeconds returns the SourceDurationSeconds field value if set, zero value otherwise.
func (o *UploadStatusResponse) GetSourceDurationSeconds() float32 {
	if o == nil || IsNil(o.SourceDurationSeconds) {
		var ret float32
		return ret
	}
	return *o.SourceDurationSeconds
}

// GetSourceDurationSecondsOk returns a tuple with the SourceDurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadStatusResponse) GetSourceDurationSecondsOk() (*float32, bool) {
	if o == nil || IsNil(o.SourceDurationSeconds) {
		return nil, false
	}
	return o.SourceDurationSeconds, true
}

// HasSourceDurationSeconds returns a boolean if a field has been set.
func (o *UploadStatusResponse) HasSourceDurationSeconds() bool {
	if o != nil && !IsNil(o.SourceDurationSeconds) {
		return true
	}

	return false
}

// SetSourceDurationSeconds gets a reference to the given float32 and assigns it to the SourceDurationSeconds field.
func (o *UploadStatusResponse) SetSourceDurationSeconds(v float32) {
	o.SourceDurationSeconds = &v
}

func (o UploadStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["file_name"] = o.FileName
	toSerialize["total_chunks"] = o.TotalChunks
	toSerialize["received_chunks"] = o.ReceivedChunks
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.SourceWidth) {
		toSerialize["source_width"] = o.SourceWidth
	}
	if !IsNil(o.SourceHeight) {
		toSerialize["source_height"] = o.SourceHeight
	}
	if !IsNil(o.SourceDurationSeconds) {
		toSerialize["source_duration_seconds"] = o.SourceDurationSeconds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UploadStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"file_name",
		"total_chunks",
		"received_chunks",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadStatusResponse := _UploadStatusResponse{}

	err = json.Unmarshal(data, &varUploadStatusResponse)

	if err != nil {
		return err
	}

	*o = UploadStatusResponse(varUploadStatusResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "file_name")
		delete(additionalProperties, "total_chunks")
		delete(additionalProperties, "received_chunks")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "source_width")
		delete(additionalProperties, "source_height")
		delete(additionalProperties, "source_duration_seconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUploadStatusResponse struct {
	value *UploadStatusResponse
	isSet bool
}

func (v NullableUploadStatusResponse) Get() *UploadStatusResponse {
	return v.value
}

func (v *NullableUploadStatusResponse) Set(val *UploadStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadStatusResponse(val *UploadStatusResponse) *NullableUploadStatusResponse {
	return &NullableUploadStatusResponse{value: val, isSet: true}
}

func (v NullableUploadStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


