/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreateUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUploadResponse{}

// CreateUploadResponse struct for CreateUploadResponse
type CreateUploadResponse struct {
	Id string `json:"id"`
	// Size of each chunk in bytes. Tiered by file size: <64 MB = whole file, <=1 GB = 8 MB, <=10 GB = 16 MB, >10 GB = 32 MB. 
	ChunkSize int64 `json:"chunk_size"`
	TotalChunks int64 `json:"total_chunks"`
	// Upload session expiry (24 hours from creation).
	ExpiresAt time.Time `json:"expires_at"`
	AdditionalProperties map[string]interface{}
}

type _CreateUploadResponse CreateUploadResponse

// NewCreateUploadResponse instantiates a new CreateUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUploadResponse(id string, chunkSize int64, totalChunks int64, expiresAt time.Time) *CreateUploadResponse {
	this := CreateUploadResponse{}
	this.Id = id
	this.ChunkSize = chunkSize
	this.TotalChunks = totalChunks
	this.ExpiresAt = expiresAt
	return &this
}

// NewCreateUploadResponseWithDefaults instantiates a new CreateUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUploadResponseWithDefaults() *CreateUploadResponse {
	this := CreateUploadResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateUploadResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateUploadResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateUploadResponse) SetId(v string) {
	o.Id = v
}

// GetChunkSize returns the ChunkSize field value
func (o *CreateUploadResponse) GetChunkSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ChunkSize
}

// GetChunkSizeOk returns a tuple with the ChunkSize field value
// and a boolean to check if the value has been set.
func (o *CreateUploadResponse) GetChunkSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkSize, true
}

// SetChunkSize sets field value
func (o *CreateUploadResponse) SetChunkSize(v int64) {
	o.ChunkSize = v
}

// GetTotalChunks returns the TotalChunks field value
func (o *CreateUploadResponse) GetTotalChunks() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalChunks
}

// GetTotalChunksOk returns a tuple with the TotalChunks field value
// and a boolean to check if the value has been set.
func (o *CreateUploadResponse) GetTotalChunksOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalChunks, true
}

// SetTotalChunks sets field value
func (o *CreateUploadResponse) SetTotalChunks(v int64) {
	o.TotalChunks = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CreateUploadResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CreateUploadResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CreateUploadResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o CreateUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["chunk_size"] = o.ChunkSize
	toSerialize["total_chunks"] = o.TotalChunks
	toSerialize["expires_at"] = o.ExpiresAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUploadResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"chunk_size",
		"total_chunks",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUploadResponse := _CreateUploadResponse{}

	err = json.Unmarshal(data, &varCreateUploadResponse)

	if err != nil {
		return err
	}

	*o = CreateUploadResponse(varCreateUploadResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "chunk_size")
		delete(additionalProperties, "total_chunks")
		delete(additionalProperties, "expires_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUploadResponse struct {
	value *CreateUploadResponse
	isSet bool
}

func (v NullableCreateUploadResponse) Get() *CreateUploadResponse {
	return v.value
}

func (v *NullableCreateUploadResponse) Set(val *CreateUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUploadResponse(val *CreateUploadResponse) *NullableCreateUploadResponse {
	return &NullableCreateUploadResponse{value: val, isSet: true}
}

func (v NullableCreateUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


