/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// OutputContainer Output container format. MP4 is widely compatible; MKV supports a broader range of audio codecs for passthrough. 
type OutputContainer string

// List of OutputContainer
const (
	MP4 OutputContainer = "mp4"
	MKV OutputContainer = "mkv"
)

// All allowed values of OutputContainer enum
var AllowedOutputContainerEnumValues = []OutputContainer{
	"mp4",
	"mkv",
}

func (v *OutputContainer) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OutputContainer(value)
	for _, existing := range AllowedOutputContainerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OutputContainer", value)
}

// NewOutputContainerFromValue returns a pointer to a valid OutputContainer
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOutputContainerFromValue(v string) (*OutputContainer, error) {
	ev := OutputContainer(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OutputContainer: valid values are %v", v, AllowedOutputContainerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OutputContainer) IsValid() bool {
	for _, existing := range AllowedOutputContainerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OutputContainer value
func (v OutputContainer) Ptr() *OutputContainer {
	return &v
}

type NullableOutputContainer struct {
	value *OutputContainer
	isSet bool
}

func (v NullableOutputContainer) Get() *OutputContainer {
	return v.value
}

func (v *NullableOutputContainer) Set(val *OutputContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputContainer(val *OutputContainer) *NullableOutputContainer {
	return &NullableOutputContainer{value: val, isSet: true}
}

func (v NullableOutputContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

