/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"fmt"
)

// checks if the ListJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListJobsResponse{}

// ListJobsResponse struct for ListJobsResponse
type ListJobsResponse struct {
	Jobs []JobResponse `json:"jobs"`
	// Opaque cursor for the next page. Null when no more results.
	NextCursor *string `json:"next_cursor,omitempty"`
	HasMore bool `json:"has_more"`
	AdditionalProperties map[string]interface{}
}

type _ListJobsResponse ListJobsResponse

// NewListJobsResponse instantiates a new ListJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListJobsResponse(jobs []JobResponse, hasMore bool) *ListJobsResponse {
	this := ListJobsResponse{}
	this.Jobs = jobs
	this.HasMore = hasMore
	return &this
}

// NewListJobsResponseWithDefaults instantiates a new ListJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListJobsResponseWithDefaults() *ListJobsResponse {
	this := ListJobsResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *ListJobsResponse) GetJobs() []JobResponse {
	if o == nil {
		var ret []JobResponse
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetJobsOk() ([]JobResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *ListJobsResponse) SetJobs(v []JobResponse) {
	o.Jobs = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *ListJobsResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ListJobsResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *ListJobsResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetHasMore returns the HasMore field value
func (o *ListJobsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListJobsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

func (o ListJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	toSerialize["has_more"] = o.HasMore

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListJobsResponse := _ListJobsResponse{}

	err = json.Unmarshal(data, &varListJobsResponse)

	if err != nil {
		return err
	}

	*o = ListJobsResponse(varListJobsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "jobs")
		delete(additionalProperties, "next_cursor")
		delete(additionalProperties, "has_more")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListJobsResponse struct {
	value *ListJobsResponse
	isSet bool
}

func (v NullableListJobsResponse) Get() *ListJobsResponse {
	return v.value
}

func (v *NullableListJobsResponse) Set(val *ListJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListJobsResponse(val *ListJobsResponse) *NullableListJobsResponse {
	return &NullableListJobsResponse{value: val, isSet: true}
}

func (v NullableListJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


