/*
SOPHON Encoding API

REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sophon

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WebhookListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookListItem{}

// WebhookListItem struct for WebhookListItem
type WebhookListItem struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Active bool `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	AdditionalProperties map[string]interface{}
}

type _WebhookListItem WebhookListItem

// NewWebhookListItem instantiates a new WebhookListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookListItem(id string, url string, active bool, createdAt time.Time) *WebhookListItem {
	this := WebhookListItem{}
	this.Id = id
	this.Url = url
	this.Active = active
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookListItemWithDefaults instantiates a new WebhookListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookListItemWithDefaults() *WebhookListItem {
	this := WebhookListItem{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookListItem) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *WebhookListItem) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookListItem) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookListItem) SetUrl(v string) {
	o.Url = v
}

// GetActive returns the Active field value
func (o *WebhookListItem) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookListItem) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookListItem) SetActive(v bool) {
	o.Active = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookListItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookListItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookListItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o WebhookListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["active"] = o.Active
	toSerialize["created_at"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"active",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookListItem := _WebhookListItem{}

	err = json.Unmarshal(data, &varWebhookListItem)

	if err != nil {
		return err
	}

	*o = WebhookListItem(varWebhookListItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "active")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookListItem struct {
	value *WebhookListItem
	isSet bool
}

func (v NullableWebhookListItem) Get() *WebhookListItem {
	return v.value
}

func (v *NullableWebhookListItem) Set(val *WebhookListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookListItem(val *WebhookListItem) *NullableWebhookListItem {
	return &NullableWebhookListItem{value: val, isSet: true}
}

func (v NullableWebhookListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


